services:
  test_postgres:
    image: postgres:17rc1-alpine
    environment:
      POSTGRES_DB: ${APP_CONFIG__TEST_DATABASE__db_name}
      POSTGRES_USER: ${APP_CONFIG__TEST_DATABASE__user}
      POSTGRES_PASSWORD: ${APP_CONFIG__TEST_DATABASE__password}
    container_name: postgresql-test-container
    ports:
      - "${APP_CONFIG__TEST_DATABASE__docker_port}:5432"
    volumes:
      - postgresql_test_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgresql_test_data: